language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

matrix:
  include:
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=9.0.x-dev
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=~8.8.0
      php: 7.2
    - env: DRUPAL_TRAVIS_DRUPAL_VERSION=~8.8.0

before_install:
  - composer global require thunder/travis

script:
  - test-drupal-project

notifications:
  email: false
